kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: code-execution
subjects:
- kind: ServiceAccount
  name: default
  namespace: code-execution
roleRef:
  kind: ClusterRole
  name: code-execution
  apiGroup: rbac.authorization.k8s.io