apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: codeexecutions.operators.psac.inf.elte.hu
spec:
  group: operators.psac.inf.elte.hu
  versions:
    - name: v1 # it's possible to provide multiple versions of a CRD
      served: true # it's possible to disable a CRD
      storage: true # there can be multiple versions but only one can be used to store the objects
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                user:
                  type: string
                codeSource:
                  type: string
                techStack:
                  type: string
                  enum: ["JDK17","GRADLE-JDK17", "MVN-JDK17", "PYTHON3","CPP17", "NODE16"]
  scope: Namespaced # resources can be namespaced or available for the whole cluster
  names:
    plural: codeexecutions
    singular: codeexecution
    kind: CodeExecution # this name is being used in manifests
    shortNames: # these short names can be used in the CLI, e.g. kubectl get er
    - ce